### ISSUE TITLE
Cannot install behind a proxy

### ISSUE THREAD

**Issue by muelli** [waawal/vagrant-elasticsearch#6]
I tried to install this box behind a proxy, but it failed:

```
> vagrant provision
==> default: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [elasticsearch | Ensure python-pycurl is installed] ********************* 
ok: [default]

TASK: [elasticsearch | Ensure Elasticsearch apt signing key is installed] ***** 
ok: [default]

TASK: [elasticsearch | Ensure Elasticsearch 1.4 repository is installed] ****** 
ok: [default]

TASK: [elasticsearch | Ensure elasticsearch is installed] ********************* 
ok: [default] => (item=openjdk-7-jre-headless,elasticsearch)

TASK: [elasticsearch | Ensure elasticsearch config is in place] *************** 
ok: [default]

TASK: [elasticsearch | Ensure elasticsearch service is enabled] *************** 
ok: [default]

TASK: [elasticsearch | Ensure head (Plugin) is installed] ********************* 
failed: [default] => {"changed": true, "cmd": ["/usr/share/elasticsearch/bin/plugin", "-install", "mobz/elasticsearch-head"], "delta": "0:00:05.689038", "end": "2015-04-23 18:13:03.707169", "rc": 74, "start": "2015-04-23 18:12:58.018131"}
stdout: -> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip...
Failed to install mobz/elasticsearch-head, reason: failed to download out of all possible locations..., use --verbose to get detailed information

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/muelli/playbook.retry

default                    : ok=7    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

it's unclear how to set a proxy variable to make this box working.

**Comment by jincod** [comment]
In logs: ES installed, but without plugin. http://localhost:9200 reachable? 

_If need plugins try install its manually https://github.com/waawal/vagrant-elasticsearch#head_

**Comment by muelli** [comment]
the problem is the ./bin/plugin which does not respect the http_proxy environment variable.  The ansible role could use smth like `-D{{ http_proxy | omit}}` (cf. http://docs.ansible.com/playbooks_filters.html#omitting-undefined-variables-and-parameters)

**Comment by muelli** [comment]
FWIW:  A change like this would it make easier to install the plugins (until https://github.com/elastic/elasticsearch/issues/11001 has been resolved)

```
- name: Ensure Inquisitor (Plugin) is installed
  command: wget -O /tmp/elasticsearch-inquisitor.zip https://github.com/polyfractal/elasticsearch-inquisitor/archive/master.zip
  args:
    creates: /tmp/elasticsearch-inquisitor.zip

- name: Install Inquisitor (Plugin)
  command:  /usr/share/elasticsearch/bin/plugin --install polyfractal/elasticsearch-inquisitor  --url file:///tmp/elasticsearch-inquisitor.zip
  args:
        creates: /usr/share/elasticsearch/plugins/inquisitor/_site/.gitignore

```
